export const PLAYER_CONFIG = {
  width: 42,
  height: 58,
  spawnX: 640,
  groundOffset: 0,
  maxGroundSpeed: 5.2,
  normalGroundDeceleration: 0.78,
  iceAcceleration: 0.08,
  iceMaxGroundSpeed: 7.4,
  wallBounceMinSpeed: 2.8,
  wallBounceMultiplier: 0.62,
  wallBounceMaxSpeed: 8.5,
  wallBounceVerticalDampening: 0.94,
  wallBounceCooldownMs: 140,
  wallBounceMaxHorizontalOverlap: 30,
  jumpMinHoldMs: 90,
  jumpMaxHoldMs: 850,
  jumpMinVelocityY: -10.8,
  jumpMaxVelocityY: -18.4,
  jumpMinVelocityX: 2.2,
  jumpMaxVelocityX: 7.8,
  groundedContactGraceMs: 90,
} as const;
